spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/juqiangh/sell-config-repo
          username: ************
          password: ************
          basedir: E:\project\config\sell\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#暴露/bus-refresh接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
